#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Verification harness for FreeConvert. Rebuilds from current build.py, then asserts:
 - file count is under Cloudflare's ~20k free cap
 - converter math is correct on rendered pages
 - every page has <title> + meta description
 - all 4 static assets exist and are referenced correctly
 - JSON-LD schema is valid
Run:  python3 verify.py
"""
import os, re, subprocess, sys, glob, json, urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
PUB  = os.path.join(ROOT, "public")

def fail(m):
    print("FAIL:", m); sys.exit(1)

# 1) Rebuild from current source
r = subprocess.run([sys.executable, os.path.join(ROOT, "build.py")],
                   capture_output=True, text=True)
if r.returncode != 0:
    fail("build.py exited %d:\n%s" % (r.returncode, r.stderr[-800:]))
print("build ok")

# 2) Assets present (hand-written, git-tracked, NOT regenerated by build.py)
for f in ["style.css", "cats.js", "conv.js", "calc.js"]:
    if not os.path.exists(os.path.join(PUB, "assets", f)):
        fail("missing asset public/assets/%s" % f)
print("assets present: 4/4")

# 3) File count within cap
nfiles = sum(len(d) for _, _, d in os.walk(PUB))
print("files:", nfiles)
if nfiles > 20000:
    fail("exceeds ~20k free file cap")
if nfiles < 10000:
    fail("unexpectedly few files")

# 4) Math spot-checks on rendered HTML
def big_of(path):
    html = open(path, encoding="utf-8").read()
    m = re.search(r'class="big">([^<]+)<', html)
    return m.group(1).strip() if m else None

def num(s):
    return float(re.sub(r'[, ]', '', s.split()[0]))

def approx(a, b, tol=1e-3):
    return abs(a - b) <= tol * max(1, abs(b))

cases = [
    ("length/meter-to-foot/10/index.html", 32.8084),
    ("temperature/celsius-to-fahrenheit/100/index.html", 212.0),
    ("weight/kilogram-to-pound/1/index.html", 2.20462),
    ("digital/gigabyte-to-megabyte/1/index.html", 1000.0),
    ("volume/liter-to-gallon-us/1/index.html", 0.264172),
    ("energy/kilocalorie-to-joule/1/index.html", 4184.0),
]
for rel, exp in cases:
    p = os.path.join(PUB, rel)
    if not os.path.exists(p):
        fail("missing page: " + rel)
    val = big_of(p)
    if val is None:
        fail("no computed answer on " + rel)
    if not approx(num(val), exp):
        fail("%s: got %s expected ~%s" % (rel, num(val), exp))
    print("math ok:", rel, "->", val)

# 5) SEO meta on sampled pages
sample = glob.glob(os.path.join(PUB, "**", "index.html"), recursive=True)[:300]
bad = sum(1 for p in sample
          if "<title>" not in open(p, encoding="utf-8").read()
          or 'name="description"' not in open(p, encoding="utf-8").read())
print("sampled pages missing title/desc:", bad, "of", len(sample))
if bad:
    fail("SEO meta missing")

# 6) Asset references resolve correctly at the origin root (no depth-broken ../assets)
bad_refs = 0
for p in sample:
    h = open(p, encoding="utf-8").read()
    # flag any asset ref that is NOT pointing at the root /assets/ path
    if re.search(r'(href|src)="[^"]*assets/', h) and '="/assets/' not in h:
        bad_refs += 1
if bad_refs:
    fail("%d pages have asset refs not under /assets/" % bad_refs)
print("asset refs under /assets/: OK")

# 7) JSON-LD valid on a pair page
pair = os.path.join(PUB, "length", "meter-to-foot", "index.html")
blob = open(pair, encoding="utf-8").read()
for m in re.findall(r'<script type="application/ld\+json">([^<]*)</script>', blob):
    try:
        json.loads(m)
    except Exception as e:
        fail("invalid JSON-LD: %s" % e)
print("JSON-LD valid: OK")

# 8) Sitemap URL count sanity (sitemap_index.xml is the canonical, with <lastmod>)
import xml.etree.ElementTree as ET
_smt = os.path.join(PUB, "sitemap_index.xml")
_root = ET.parse(_smt).getroot()
urls = len([e for e in _root.iter("{http://www.sitemaps.org/schemas/sitemap/0.9}loc")])
print("sitemap urls:", urls)
if urls < 15000:
    fail("sitemap too small")

print("\nALL CHECKS PASSED")
